/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * An Item is something a user may purchase.
 *
 * @export
 * @interface Item
 */
export interface Item {

    /**
     * UUID representation of the item's ID
     *
     * @type {string}
     * @memberof Item
     */
    id: string;

    /**
     * The name of the item
     *
     * @type {string}
     * @memberof Item
     */
    name: string;

    /**
     * The universal product code of the item
     *
     * @type {string}
     * @memberof Item
     */
    upc?: string;

    /**
     * The ID of the category to which this item belongs
     *
     * @type {string}
     * @memberof Item
     */
    categoryId?: string;
}
