/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListsListIdBody
 */
export interface ListsListIdBody {

    /**
     * @type {number}
     * @memberof ListsListIdBody
     */
    ordinal: number;

    /**
     * @type {string}
     * @memberof ListsListIdBody
     */
    shopperId: string;

    /**
     * @type {string}
     * @memberof ListsListIdBody
     */
    groupId: string;

    /**
     * @type {string}
     * @memberof ListsListIdBody
     */
    name: string;
}
