/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickListExcludeKeyofListId_
 */
export interface PickListExcludeKeyofListId_ {

    /**
     * The name of the list
     *
     * @type {string}
     * @memberof PickListExcludeKeyofListId_
     */
    name: string;

    /**
     * The shopper that originally created the list
     *
     * @type {string}
     * @memberof PickListExcludeKeyofListId_
     */
    ownerId: string;

    /**
     * The group of users with whom this list is shared
     *
     * @type {string}
     * @memberof PickListExcludeKeyofListId_
     */
    groupId?: string;
}
