/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GroupMembers } from './group-members';
 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickGroupIdOrMembers_
 */
export interface PickGroupIdOrMembers_ {

    /**
     * UUID representation of the groups's ID
     *
     * @type {string}
     * @memberof PickGroupIdOrMembers_
     */
    id: string;

    /**
     * @type {GroupMembers}
     * @memberof PickGroupIdOrMembers_
     */
    members: GroupMembers;
}
