/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickShopperExcludeKeyofShopperId_
 */
export interface PickShopperExcludeKeyofShopperId_ {

    /**
     * The first name of the shopper
     *
     * @type {string}
     * @memberof PickShopperExcludeKeyofShopperId_
     */
    firstName: string;

    /**
     * The last name of the shopper
     *
     * @type {string}
     * @memberof PickShopperExcludeKeyofShopperId_
     */
    lastName: string;

    /**
     * The email of the shopper
     *
     * @type {string}
     * @memberof PickShopperExcludeKeyofShopperId_
     */
    email: string;
}
