/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickItemIdOrNameOrUpc_
 */
export interface PickItemIdOrNameOrUpc_ {

    /**
     * UUID representation of the item's ID
     *
     * @type {string}
     * @memberof PickItemIdOrNameOrUpc_
     */
    id: string;

    /**
     * The name of the item
     *
     * @type {string}
     * @memberof PickItemIdOrNameOrUpc_
     */
    name: string;

    /**
     * The universal product code of the item
     *
     * @type {string}
     * @memberof PickItemIdOrNameOrUpc_
     */
    upc?: string;
}
