/* tslint:disable */
/* eslint-disable */
/**
 * pantryplus-api
 * This is the API layer for the PantryPlus mobile app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Shopper } from './shopper';
 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickGroupIdOrNameOrOwner_
 */
export interface PickGroupIdOrNameOrOwner_ {

    /**
     * UUID representation of the group's ID
     *
     * @type {string}
     * @memberof PickGroupIdOrNameOrOwner_
     */
    id: string;

    /**
     * The name of the group
     *
     * @type {string}
     * @memberof PickGroupIdOrNameOrOwner_
     */
    name: string;

    /**
     * @type {Shopper}
     * @memberof PickGroupIdOrNameOrOwner_
     */
    owner: Shopper;
}
